version: "3.3"

services:
  python:
    build: .
    container_name: py-dev
    volumes:
      - type: bind
        source: "$PWD/../code"
        target: /app
    stdin_open: true
    tty: true
    command: zsh
