version: "3.3"

services:
  thesis:
    build: .
    container_name: thesis
    volumes:
      - type: bind
        source: "$PWD/../code"
        target: /app
    stdin_open: true
    tty: true
    command: zsh
